export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";

export const INCREMENT_ITEM_IN_CART = "INCREMENT_ITEM_IN_CART";
export const DECREMENT_ITEM_IN_CART = "DECREMENT_ITEM_IN_CART";
